language: node_js

os:
  - osx
  - linux

git:
  clone: false

before_script:
  - npm install -g jest
  - npm install --dev @babel/core @babel/preset-env babel-jest

branches:
  only:
  - master
  - develop
  - ci